# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_payload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tracer_payload_pb2 as tracer__payload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_payload.proto\x1a\x14tracer_payload.proto\"\x80\x02\n\x0c\x41gentPayload\x12\x10\n\x08hostName\x18\x01 \x01(\t\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t\x12&\n\x0etracerPayloads\x18\x05 \x03(\x0b\x32\x0e.TracerPayload\x12%\n\x04tags\x18\x06 \x03(\x0b\x32\x17.AgentPayload.TagsEntry\x12\x14\n\x0c\x61gentVersion\x18\x07 \x01(\t\x12\x11\n\ttargetTPS\x18\x08 \x01(\x01\x12\x10\n\x08\x65rrorTPS\x18\t \x01(\x01\x12\x1a\n\x12rareSamplerEnabled\x18\n \x01(\x08\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x16Z\x14pkg/proto/pbgo/traceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_payload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024pkg/proto/pbgo/trace'
  _AGENTPAYLOAD_TAGSENTRY._options = None
  _AGENTPAYLOAD_TAGSENTRY._serialized_options = b'8\001'
  _AGENTPAYLOAD._serialized_start=46
  _AGENTPAYLOAD._serialized_end=302
  _AGENTPAYLOAD_TAGSENTRY._serialized_start=259
  _AGENTPAYLOAD_TAGSENTRY._serialized_end=302
# @@protoc_insertion_point(module_scope)
