# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: span.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspan.proto\"\xc6\x01\n\x08SpanLink\x12\x0f\n\x07traceID\x18\x01 \x01(\x04\x12\x14\n\x0ctraceID_high\x18\x02 \x01(\x04\x12\x0e\n\x06spanID\x18\x03 \x01(\x04\x12-\n\nattributes\x18\x04 \x03(\x0b\x32\x19.SpanLink.AttributesEntry\x12\x12\n\ntracestate\x18\x05 \x01(\t\x12\r\n\x05\x66lags\x18\x06 \x01(\r\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc6\x03\n\x04Span\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08resource\x18\x03 \x01(\t\x12\x0f\n\x07traceID\x18\x04 \x01(\x04\x12\x0e\n\x06spanID\x18\x05 \x01(\x04\x12\x10\n\x08parentID\x18\x06 \x01(\x04\x12\r\n\x05start\x18\x07 \x01(\x03\x12\x10\n\x08\x64uration\x18\x08 \x01(\x03\x12\r\n\x05\x65rror\x18\t \x01(\x05\x12\x1d\n\x04meta\x18\n \x03(\x0b\x32\x0f.Span.MetaEntry\x12#\n\x07metrics\x18\x0b \x03(\x0b\x32\x12.Span.MetricsEntry\x12\x0c\n\x04type\x18\x0c \x01(\t\x12*\n\x0bmeta_struct\x18\r \x03(\x0b\x32\x15.Span.MetaStructEntry\x12\x1c\n\tspanLinks\x18\x0e \x03(\x0b\x32\t.SpanLink\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x31\n\x0fMetaStructEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\x16Z\x14pkg/proto/pbgo/traceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'span_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024pkg/proto/pbgo/trace'
  _SPANLINK_ATTRIBUTESENTRY._options = None
  _SPANLINK_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _SPAN_METAENTRY._options = None
  _SPAN_METAENTRY._serialized_options = b'8\001'
  _SPAN_METRICSENTRY._options = None
  _SPAN_METRICSENTRY._serialized_options = b'8\001'
  _SPAN_METASTRUCTENTRY._options = None
  _SPAN_METASTRUCTENTRY._serialized_options = b'8\001'
  _SPANLINK._serialized_start=15
  _SPANLINK._serialized_end=213
  _SPANLINK_ATTRIBUTESENTRY._serialized_start=164
  _SPANLINK_ATTRIBUTESENTRY._serialized_end=213
  _SPAN._serialized_start=216
  _SPAN._serialized_end=670
  _SPAN_METAENTRY._serialized_start=528
  _SPAN_METAENTRY._serialized_end=571
  _SPAN_METRICSENTRY._serialized_start=573
  _SPAN_METRICSENTRY._serialized_end=619
  _SPAN_METASTRUCTENTRY._serialized_start=621
  _SPAN_METASTRUCTENTRY._serialized_end=670
# @@protoc_insertion_point(module_scope)
