# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracer_payload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import span_pb2 as span__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tracer_payload.proto\x1a\nspan.proto\"\xac\x01\n\nTraceChunk\x12\x10\n\x08priority\x18\x01 \x01(\x05\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12\x14\n\x05spans\x18\x03 \x03(\x0b\x32\x05.Span\x12#\n\x04tags\x18\x04 \x03(\x0b\x32\x15.TraceChunk.TagsEntry\x12\x14\n\x0c\x64roppedTrace\x18\x05 \x01(\x08\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa2\x02\n\rTracerPayload\x12\x13\n\x0b\x63ontainerID\x18\x01 \x01(\t\x12\x14\n\x0clanguageName\x18\x02 \x01(\t\x12\x17\n\x0flanguageVersion\x18\x03 \x01(\t\x12\x15\n\rtracerVersion\x18\x04 \x01(\t\x12\x11\n\truntimeID\x18\x05 \x01(\t\x12\x1b\n\x06\x63hunks\x18\x06 \x03(\x0b\x32\x0b.TraceChunk\x12&\n\x04tags\x18\x07 \x03(\x0b\x32\x18.TracerPayload.TagsEntry\x12\x0b\n\x03\x65nv\x18\x08 \x01(\t\x12\x10\n\x08hostname\x18\t \x01(\t\x12\x12\n\nappVersion\x18\n \x01(\t\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x16Z\x14pkg/proto/pbgo/traceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracer_payload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024pkg/proto/pbgo/trace'
  _TRACECHUNK_TAGSENTRY._options = None
  _TRACECHUNK_TAGSENTRY._serialized_options = b'8\001'
  _TRACERPAYLOAD_TAGSENTRY._options = None
  _TRACERPAYLOAD_TAGSENTRY._serialized_options = b'8\001'
  _TRACECHUNK._serialized_start=37
  _TRACECHUNK._serialized_end=209
  _TRACECHUNK_TAGSENTRY._serialized_start=166
  _TRACECHUNK_TAGSENTRY._serialized_end=209
  _TRACERPAYLOAD._serialized_start=212
  _TRACERPAYLOAD._serialized_end=502
  _TRACERPAYLOAD_TAGSENTRY._serialized_start=166
  _TRACERPAYLOAD_TAGSENTRY._serialized_end=209
# @@protoc_insertion_point(module_scope)
